/*
 *  Problem 2
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * 
 * */

#include<stdio.h>

int fibonacci_array(int n) {
	int a[2];
	int i;
	a[0] = 1;
	a[1] = 2;
	if(n==0)
		return 1;
	else if(n==1)
		return 2;
	else {
		for(i=0; i<n/2; i++) {
			a[0] = a[0] + a[1];
			a[1] = a[0] + a[1];
		}
	}
	if(n%2!=0)
		return a[1];
	else if(n%2==0)
		return a[0];
}

int main() {
	int count, sum;
	count = 0;
	sum = 0;
	int i;
	while(fibonacci_array(count)<4000000) {
		printf("%d ", fibonacci_array(count));
		if(fibonacci_array(count)%2==0) {
			sum += fibonacci_array(count);
		}
		count += 1;
	}
	
	printf("the sum is: %d\n", sum);
	return 0;
}
